# Generated by Django 3.2.8 on 2021-10-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterbusiness',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='mastercustomer',
            options={'verbose_name_plural': 'Customers'},
        ),
    ]
